"""Report generator - outputs collision results as Markdown."""

import os
from datetime import datetime


def generate_report(result: dict, output_dir: str = "output") -> str:
    """Generate a Markdown report from collision result."""
    os.makedirs(output_dir, exist_ok=True)

    topic = result["topic"]
    history = result["history"]
    synthesis = result["synthesis"]
    review = result["review"]
    session_id = result.get("session_id", "")

    # Build filename
    safe_topic = topic[:30].replace(" ", "_").replace("/", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"collision_{safe_topic}_{timestamp}.md"
    filepath = os.path.join(output_dir, filename)

    # Build content
    lines = [
        f"# 🧠 Idea Collision Report",
        f"",
        f"**主题**: {topic}",
        f"**时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**智能体数**: {len(set(e['agent'] for e in history))}",
        f"**碰撞轮次**: {len(set(e['round'] for e in history if isinstance(e['round'], int)))}",
        f"",
        f"---",
        f"",
        f"## 📝 碰撞过程",
        f"",
    ]

    # Group by round
    rounds = {}
    for entry in history:
        r = entry["round"]
        if r not in rounds:
            rounds[r] = []
        rounds[r].append(entry)

    round_names = {
        1: "初始想法生成",
        2: "碰撞交锋 · 第一轮",
        3: "碰撞交锋 · 第二轮",
        4: "碰撞交锋 · 第三轮",
        "final": "最终融合",
        "review": "方案审查",
    }

    for r, entries in rounds.items():
        label = round_names.get(r, f"Round {r}")
        lines.append(f"### Round {r}: {label}")
        lines.append("")
        for entry in entries:
            agent = entry["agent"]
            content = entry["content"]
            if isinstance(content, list):
                content = "\n".join(f"- {c}" for c in content)
            lines.append(f"**{agent}**")
            lines.append("")
            lines.append(content)
            lines.append("")
        lines.append("---")
        lines.append("")

    # Final synthesis
    lines.extend([
        f"## 🎯 最终融合方案",
        f"",
        synthesis,
        f"",
        f"---",
        f"",
        f"## 🔍 方案审查（批评家）",
        f"",
        review,
        f"",
        f"---",
        f"",
        f"*Generated by Idea Collision System*",
    ])

    content = "\n".join(lines)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath
